import { useState } from 'react';

function ShareInvoiceModal({
  invoice,
  invoices = [],
  company,
  defaultMode = 'pdf', // 'pdf', 'email', 'sms', 'print'
  onDownloadPDF,
  onClose
}) {
  const [selectedInvoiceId, setSelectedInvoiceId] = useState(invoice?.id || (invoices[0]?.id ?? ''));
  const [copied, setCopied] = useState(false);

  const targetInvoice = invoices.find((i) => i.id === selectedInvoiceId) || invoice || invoices[0];

  const customerName = targetInvoice?.customerName || 'Customer';
  const customerPhone = targetInvoice?.customerPhone || '';
  const invoiceNo = targetInvoice?.invoiceNumber || 'INV-001';
  const totalAmount = targetInvoice?.totals?.total?.toFixed(2) || '0.00';
  const companyName = company?.name || 'Priya Sales';

  const smsText = `Dear ${customerName}, your tax invoice #${invoiceNo} for amount Rs. ${totalAmount} is generated by ${companyName}. Thank you for your business!`;

  const emailSubject = `Tax Invoice #${invoiceNo} from ${companyName}`;
  const emailBody = `Dear ${customerName},\n\nPlease find your tax invoice details below:\n\nInvoice Number: ${invoiceNo}\nDate: ${targetInvoice?.invoiceDate || ''}\nTotal Amount: Rs. ${totalAmount}\n\nThank you for choosing ${companyName}!\n\nBest regards,\n${companyName}`;

  const mailtoLink = `mailto:${encodeURIComponent(targetInvoice?.customerEmail || '')}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
  const whatsappLink = `https://wa.me/${customerPhone.replace(/[^0-9]/g, '')}?text=${encodeURIComponent(smsText)}`;

  const handleCopyText = (text) => {
    navigator.clipboard?.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    if (targetInvoice && onDownloadPDF) {
      onDownloadPDF(targetInvoice);
    }
  };

  return (
    <div className="modal show d-block" tabIndex="-1" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
      <div className="modal-dialog modal-lg modal-dialog-centered">
        <div className="modal-content shadow-lg border-0">
          <div className="modal-header bg-primary text-white">
            <h5 className="modal-title">
              {defaultMode === 'email' && '📧 Email Invoice'}
              {defaultMode === 'sms' && '📱 Send SMS / WhatsApp Invoice'}
              {defaultMode === 'print' && '🖨️ Print Invoice'}
              {defaultMode === 'pdf' && '📥 Download PDF Tax Invoice'}
            </h5>
            <button type="button" className="btn-close btn-close-white" onClick={onClose} />
          </div>

          <div className="modal-body p-4">
            {/* Invoice Selector */}
            {invoices.length > 1 && (
              <div className="mb-4">
                <label className="form-label fw-semibold">Select Invoice:</label>
                <select
                  className="form-select"
                  value={selectedInvoiceId}
                  onChange={(e) => setSelectedInvoiceId(e.target.value)}
                >
                  {invoices.map((inv) => (
                    <option key={inv.id} value={inv.id}>
                      {inv.invoiceNumber} - {inv.customerName || 'Walk-in'} (₹{inv.totals?.total?.toFixed(2) || '0'}) - {inv.invoiceDate}
                    </option>
                  ))}
                </select>
              </div>
            )}

            {targetInvoice ? (
              <>
                <div className="p-3 bg-light rounded-3 mb-4 border">
                  <div className="row g-2 small">
                    <div className="col-sm-6">
                      <strong>Invoice #:</strong> {targetInvoice.invoiceNumber}
                    </div>
                    <div className="col-sm-6">
                      <strong>Date:</strong> {targetInvoice.invoiceDate}
                    </div>
                    <div className="col-sm-6">
                      <strong>Customer:</strong> {targetInvoice.customerName || 'Walk-in'}
                    </div>
                    <div className="col-sm-6">
                      <strong>Grand Total:</strong> ₹{targetInvoice.totals?.total?.toFixed(2)}
                    </div>
                  </div>
                </div>

                {/* Email Section */}
                {defaultMode === 'email' && (
                  <div>
                    <div className="mb-3">
                      <label className="form-label fw-semibold">Subject</label>
                      <input type="text" className="form-control" readOnly value={emailSubject} />
                    </div>
                    <div className="mb-3">
                      <label className="form-label fw-semibold">Message Body</label>
                      <textarea className="form-control" rows="5" readOnly value={emailBody} />
                    </div>
                    <div className="d-flex gap-2">
                      <a href={mailtoLink} className="btn btn-primary">
                        🚀 Open in Mail Client
                      </a>
                      <button
                        type="button"
                        className="btn btn-outline-secondary"
                        onClick={() => handleCopyText(emailBody)}
                      >
                        {copied ? '✓ Copied!' : '📋 Copy Body'}
                      </button>
                    </div>
                  </div>
                )}

                {/* SMS / WhatsApp Section */}
                {defaultMode === 'sms' && (
                  <div>
                    <div className="mb-3">
                      <label className="form-label fw-semibold">Notification Text</label>
                      <textarea className="form-control" rows="4" readOnly value={smsText} />
                    </div>
                    <div className="d-flex gap-2 flex-wrap">
                      {customerPhone && (
                        <a
                          href={whatsappLink}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="btn btn-success"
                        >
                          💬 Send via WhatsApp
                        </a>
                      )}
                      <button
                        type="button"
                        className="btn btn-outline-secondary"
                        onClick={() => handleCopyText(smsText)}
                      >
                        {copied ? '✓ Copied!' : '📋 Copy SMS Text'}
                      </button>
                    </div>
                  </div>
                )}

                {/* PDF / Print Section */}
                {(defaultMode === 'pdf' || defaultMode === 'print') && (
                  <div className="text-center py-3">
                    <p className="text-muted">
                      Generate and download an official high-resolution GST tax invoice in PDF format ready for print and accounting.
                    </p>
                    <button
                      type="button"
                      className="btn btn-primary btn-lg px-4"
                      onClick={handlePrint}
                    >
                      📥 Generate & Download PDF
                    </button>
                  </div>
                )}
              </>
            ) : (
              <div className="text-center py-4 text-muted">
                No invoices available to share. Please create an invoice first.
              </div>
            )}
          </div>

          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ShareInvoiceModal;
